### PR TITLE
Added Learning Sample

### PR DESCRIPTION
**Pull request by sameyada**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Please check if the PR fulfills these requirements
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

#### (Bug fix, feature, docs update, ...)

`Added a new learning sample widget which is a replica of popular finesse learning sample gadget that helps in understanding the basics of gadgets`

#### (You can link to an open issue)

`[Type here]`

#### (if this is a feature change)?

`[Type here]`

#### (What changes might users need to make in their application due to this PR?)

`NO`

## Other information:

`NA`

### CODE REVIEW

**Comment by yananym** [comment]
So how is this different from Lit Element widget starter?

**Comment by sameyada** [comment]
This is replica of a popular Finesse gadget so people can compare, understand and learn.

**Comment by futurethang** [comment]
I agree that this seems to cause a bit of duplication in the wrong area. What if we made the changes to the documentation at the top level, the lit-element starter directory, so people get that help with building the dist and adding it to their project config. For the Finesse widget, I'd say make it a full implementation of the known gadget as a web component following the Lit Element structure, but not just a hypothetical sample.

**Comment by yananym** [comment]
> I agree that this seems to cause a bit of duplication in the wrong area. What if we made the changes to the documentation at the top level, the lit-element starter directory, so people get that help with building the dist and adding it to their project config. For the Finesse widget, I'd say make it a full implementation of the known gadget as a web component following the Lit Element structure, but not just a hypothetical sample.

Agreed with Kevin

**Comment by elenagiere** [comment]
> I agree that this seems to cause a bit of duplication in the wrong area. What if we made the changes to the documentation at the top level, the lit-element starter directory, so people get that help with building the dist and adding it to their project config. For the Finesse widget, I'd say make it a full implementation of the known gadget as a web component following the Lit Element structure, but not just a hypothetical sample.

I agree with Kevin

**Comment by sameyada** [comment]
If someone knows the finesse learning gadget he can easily understand what change he need to do achieve similar functionality .This is purely to build an understanding .Even if it is duplicate it is just an example and it is not causing any harm to the users desktop. I have added readme notes on building the project so it is not dependent on the lit element starter directory and its documentation.

**Comment by futurethang** [comment]
@sameyada I think what we are missing here then is a fully working sample that users can launch locally like the other current Example widgets. I'm unable to get the widget to run myself, so perhaps I am missing something?

**Review by merajcal — APPROVED** [review]

**Pull request merged**
